2022/01/31 21:36:16 [emerg] 58#58: io_setup() failed (38: Function not implemented)
2022/01/31 21:36:16 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 21:36:16 [emerg] 60#60: io_setup() failed (38: Function not implemented)
2022/01/31 21:36:16 [emerg] 56#56: io_setup() failed (38: Function not implemented)
2022/01/31 21:37:05 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/01/31 21:37:05 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/01/31 21:39:37 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 21:39:37 [emerg] 59#59: io_setup() failed (38: Function not implemented)
2022/01/31 21:39:37 [emerg] 57#57: io_setup() failed (38: Function not implemented)
2022/01/31 21:39:37 [emerg] 60#60: io_setup() failed (38: Function not implemented)
2022/01/31 21:40:03 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /_profiler/275d28?panel=config HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "http://localhost/"
2022/01/31 21:40:05 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /_profiler/275d28?panel=config HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "http://localhost/"
2022/01/31 21:40:06 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:07 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:08 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:08 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:08 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:09 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:09 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:20 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:46 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 21:40:46 [emerg] 59#59: io_setup() failed (38: Function not implemented)
2022/01/31 21:40:46 [emerg] 57#57: io_setup() failed (38: Function not implemented)
2022/01/31 21:40:46 [emerg] 58#58: io_setup() failed (38: Function not implemented)
2022/01/31 21:40:54 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:40:55 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:41:04 [error] 61#61: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/01/31 21:41:39 [emerg] 60#60: io_setup() failed (38: Function not implemented)
2022/01/31 21:41:39 [emerg] 57#57: io_setup() failed (38: Function not implemented)
2022/01/31 21:41:39 [emerg] 62#62: io_setup() failed (38: Function not implemented)
2022/01/31 21:41:39 [emerg] 59#59: io_setup() failed (38: Function not implemented)
2022/01/31 21:41:50 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/01/31 21:41:51 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/01/31 21:41:51 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/01/31 21:41:52 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/01/31 21:42:07 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:42:08 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:42:08 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:42:08 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:42:15 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:42:15 [error] 57#57: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:42:56 [emerg] 57#57: io_setup() failed (38: Function not implemented)
2022/01/31 21:42:56 [emerg] 59#59: io_setup() failed (38: Function not implemented)
2022/01/31 21:42:56 [emerg] 62#62: io_setup() failed (38: Function not implemented)
2022/01/31 21:42:56 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 21:43:03 [error] 59#59: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:43:04 [error] 59#59: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:43:04 [error] 59#59: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:43:14 [error] 62#62: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "127.0.0.1"
2022/01/31 21:43:15 [error] 62#62: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/01/31 21:43:16 [error] 62#62: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "127.0.0.1"
2022/01/31 21:43:16 [error] 62#62: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/01/31 21:43:23 [error] 62#62: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "127.0.0.1"
2022/01/31 21:43:23 [error] 62#62: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/01/31 21:45:57 [emerg] 56#56: io_setup() failed (38: Function not implemented)
2022/01/31 21:45:57 [emerg] 58#58: io_setup() failed (38: Function not implemented)
2022/01/31 21:45:57 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 21:45:57 [emerg] 60#60: io_setup() failed (38: Function not implemented)
2022/01/31 21:46:11 [error] 58#58: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:46:11 [error] 58#58: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:46:47 [error] 58#58: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2022/01/31 21:47:29 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 21:47:29 [emerg] 60#60: io_setup() failed (38: Function not implemented)
2022/01/31 21:47:29 [emerg] 58#58: io_setup() failed (38: Function not implemented)
2022/01/31 21:47:29 [emerg] 56#56: io_setup() failed (38: Function not implemented)
2022/01/31 21:47:29 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 21:47:30 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 21:47:34 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 21:47:35 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 21:47:37 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 21:47:38 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 21:47:40 [error] 61#61: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/01/31 22:18:36 [emerg] 77#77: io_setup() failed (38: Function not implemented)
2022/01/31 22:18:36 [emerg] 79#79: io_setup() failed (38: Function not implemented)
2022/01/31 22:18:36 [emerg] 82#82: io_setup() failed (38: Function not implemented)
2022/01/31 22:18:36 [emerg] 81#81: io_setup() failed (38: Function not implemented)
2022/01/31 22:25:11 [emerg] 59#59: io_setup() failed (38: Function not implemented)
2022/01/31 22:25:11 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 22:25:11 [emerg] 64#64: io_setup() failed (38: Function not implemented)
2022/01/31 22:25:11 [emerg] 63#63: io_setup() failed (38: Function not implemented)
2022/01/31 23:00:00 [emerg] 61#61: io_setup() failed (38: Function not implemented)
2022/01/31 23:00:00 [emerg] 59#59: io_setup() failed (38: Function not implemented)
2022/01/31 23:00:00 [emerg] 63#63: io_setup() failed (38: Function not implemented)
2022/01/31 23:00:00 [emerg] 64#64: io_setup() failed (38: Function not implemented)
2022/02/02 11:30:46 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:30:46 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:31:00 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:31:00 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:31:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:31:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:31:22 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:31:22 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:31:23 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:31:24 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:32:12 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:32:13 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:32:14 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:32:14 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:32:15 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:32:16 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:32:16 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:32:17 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:32:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:32:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2022/02/02 11:33:43 [error] 34#34: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:33:43 [error] 34#34: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:33:52 [error] 34#34: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:33:53 [error] 34#34: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:33:56 [error] 34#34: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:33:56 [error] 34#34: *26 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:35:31 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:35:31 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:35:32 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:35:33 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:35:37 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:35:37 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:35:39 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost"
2022/02/02 11:35:39 [error] 34#34: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "localhost", referrer: "http://localhost/"
2022/02/02 11:35:45 [error] 34#34: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1"
2022/02/02 11:35:46 [error] 34#34: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
